server:
  port: 8080
spring:
  profiles:
    active: local
    group:
      dev:
        - dev
      prod:
        - prod
      local:
        - local

api:
  naver:
    baseUrl: https://openapi.naver.com
    clientId: cR3FUPmbWePE93_yOtlN
    clientSecret: KBk5ElmurU


--- # dev
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gcp.connect.psdb.cloud
    username: blu00ywa99iq6d09zhju
    password: pscale_pw_cLj7rCsrLdBKXjd50E9n59ymJkefz1yimlajGlOjil5

logging:
  level:
    kr.co.dbsg: info

--- # local
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: id
    password: pw
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    kr.co.dbsg: debug
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
